### ISSUE TITLE
Any chance of a serverside websocket client implementation?

### ISSUE THREAD

**Issue by zanechua** [TheOrchid/WebSocket#16]
Hey! 

Thanks for the great library.

Really easy to use and setup and get it running including the supervisor template.

Any chance that you can write a serverside form of a websocket client?

I need to communicate via a traditional rest api and send data to a client but the websocket layer and laravel layer are detached so there's no way to do that except via a websocket client broadcast, wonder if you had any intentions?

**Comment by tabuna** [comment]
Hi, I do not yet have this in my plans for the near future

**Comment by aios** [comment]
@zanechua use centrifugo

**Comment by zanechua** [comment]
@aios I ended up using wrench!
